### ISSUE TITLE
can't find this plugin in latest kong

### ISSUE THREAD

**Issue by thewaytoai** [Kong/kong-plugin-grpc-web#1]
I see the grpc-web plugin is inside the kong of 1.4x/1.5x/2.0x version in this page:https://docs.konghq.com/hub/kong-inc/grpc-web/,
but why i install this kind of version of kong docker, I can't find the plugin?

**Comment by thewaytoai** [comment]
Do I have to put this plugin to my own kong plugins directory?

**Comment by pravin-raha** [comment]
I don't think they have bundled it with kong yet. If you want you can add it via luarocks `luarocks install kong-plugin-grpc-web`

**Comment by hutchic** [comment]
This plugin is available in the 2.1.0-alpha.1 which you can find here: https://hub.docker.com/r/kong/kong/tags?page=1&name=2.1.0
