### ISSUE TITLE
Please provide installation details especially in Docker environment

### ISSUE THREAD

**Issue by huynhthanhbinh** [Kong/kong-plugin-grpc-web#2]

**Comment by hutchic** [comment]
This plugin is available in the 2.1.0-alpha.1 which you can find here: https://hub.docker.com/r/kong/kong/tags?page=1&name=2.1.0

If you're trying to install this plugin in a earlier version of Kong follow the instructions outlined [here](https://github.com/Kong/docker-kong/tree/master/customize#customize-kong-by-injecting-plugins-and-templates)
